#!/usr/bin/env node
"use strict";

/**
 * Build the browser bundle for the web checker at opusmill.com/check.
 *
 * This does not transform the source. It inlines lib/rules.js, lib/core.js
 * and lib/fix.js
 * verbatim inside a four-line CommonJS shim, so the page runs exactly the code
 * the CLI runs. A rewritten or hand-ported copy would drift within a week, and
 * then the web checker and `winbreak` would disagree about someone's code —
 * which is worse than having no web checker at all.
 *
 * `npm run build:web` writes it. `npm test` fails if it is stale.
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
// Inside the repo, not next to it. An earlier version wrote straight into
// the website's directory, which meant a fresh clone had no bundle and the
// staleness test below failed in CI on a machine where nothing was wrong.
const OUT_DIR = path.join(ROOT, "web");
const OUT = path.join(OUT_DIR, "winbreak.bundle.js");

function buildSource() {
  const rules = fs.readFileSync(path.join(ROOT, "lib", "rules.js"), "utf8");
  const core = fs.readFileSync(path.join(ROOT, "lib", "core.js"), "utf8");
  const fix = fs.readFileSync(path.join(ROOT, "lib", "fix.js"), "utf8");
  const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8"));

  return `/* winbreak ${pkg.version} — generated by scripts/build-web.js. Do not edit.
   Source: github.com/Hackierz/winbreak  ·  MIT
   lib/rules.js and lib/core.js are inlined verbatim, so this runs the same
   code as the CLI. Regenerate with: npm run build:web */
(function (global) {
  "use strict";
  var cache = {};
  var defs = {};
  function define(name, fn) { defs[name] = fn; }
  function require(name) {
    var key = name.replace(/^\\.\\//, "");
    if (cache[key]) return cache[key].exports;
    var m = cache[key] = { exports: {} };
    defs[key](m, m.exports, require);
    return m.exports;
  }

  define("rules", function (module, exports, require) {
${rules}
  });

  define("core", function (module, exports, require) {
${core}
  });

  define("fix", function (module, exports, require) {
${fix}
  });

  var core = require("./core");
  var fix = require("./fix");
  global.winbreak = {
    version: ${JSON.stringify(pkg.version)},
    scanSource: core.scanSource,
    rules: require("./rules").rules,
    fixScript: fix.fixScript,
    fixPackageJson: fix.fixPackageJson,
    applyToText: fix.applyToText,
    fixNeeds: fix.NEEDS,
  };
})(typeof window !== "undefined" ? window : this);
`;
}

if (require.main === module) {
  const src = buildSource();
  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(OUT, src);
  const kb = (Buffer.byteLength(src) / 1024).toFixed(1);
  console.log(`wrote ${path.relative(process.cwd(), OUT)} (${kb} kB)`);
}

module.exports = { buildSource, OUT, OUT_DIR };
